/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};


// navbar: {
//   title: 'Ohana',
//   logo: {
//     alt: 'Ohana Logo',
//     src: 'img/docusaurus.png',
//   },
//   items: [
//     {
//       type: 'doc',
//       docId: 'intro',
//       position: 'left',
//       label: 'Tutorial',
//     },
//     {to: '/blog', label: 'Blog', position: 'left'},
//     {to: '/meet-the-team', label: 'Meet The Team', position: 'right'},
//     {
//       href: 'https://github.com/oslabs-beta/ohana',
//       label: 'GitHub',
//       position: 'right',
//     },
//   ],
// },